### ISSUE TITLE
TODO#1: Reject inputs

### ISSUE THREAD

**Issue by iigmir** [iigmir/kotonoha-daisuke#1]
Reject inputs that are not from dq.yam.com.

```
node https://www.gov.uk
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'C:\Users\iigmir\Desktop\KotonohaDaisuke\https:\www.gov.uk'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by iigmir** [comment]
Fixed in the commit 5802a37
